---

- name: Setup or update all remote raspberries
  hosts: remote_raspberries
  remote_user: pi
  become: yes

  tasks:
    
    # set timezone

    - name: Set timezone to Europe/Paris
      timezone:
        name: Europe/Paris

    # set hostname

    - hostname:
        name: "{{ host_name }}"
        use: debian

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: 127.0.1.1   {{ host_name }}

    # setup ssh server with public key, remove text password authentication

    - name: Update authorized public key 
      authorized_key: 
        user: pi 
        key: "{{ lookup('file', '/Volumes/Vault2/ssh-keys/pi.wo.password/pi.raspberry.pub') }}" 
        state: present

    - name: Swith PasswordAuthentication to 'no' in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: PasswordAuthentication no

    - name: Restart ssh service
      service:
        name: ssh
        state: restarted

    # all packages update

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    # Install required packages

    - name: Install ntfs packages
      apt:
        name: ntfs-3g
        state: present

    - name: Install samba packages
      apt:
        name: samba
        state: present

    - name: Install rsync packages
      apt:
        name: rsync
        state: present

    - name: Install hdparm packages, for drive standby
      apt:
        name: hdparm
        state: present

    # Mount the NTFS USB drive disk

    - name: Create mount directory 
      file:
        path: /mnt/backup
        state: directory

    - name: Mount up device by UUID
      mount:
        path: /mnt/backup
        src: "UUID={{ host_usb_hd_uuid }}"
        fstype: ntfs
        opts: rw,defaults
        state: present

    # Drive spindown when idle

    - name: Add configuration to /etc/hdparm.conf
      blockinfile:
        path: /etc/hdparm.conf
        marker: "# {mark} Spindown when idle"
        block: |
          {{ host_usb_drive_name }} {
            write_cache = {{ host_usb_drive_write_cache }}
            spindown_time = {{ host_usb_drive_spindown_time }}
          }

    # Samba setup

    - name: Add share conf to /etc/samba/smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [{{ samba_share_name }}]
              comment = {{ samba_share_name }}
              path = /mnt/backup
              browsable = yes
              guest ok = yes
              read only = no
              create mask = 0755

    - name: restart smbd
      command: smbd restart
      register: output

    - name: restart nmbd
      command: nmbd restart
      register: output

    # Copy bash scripts (utlities)
    - copy:
        src: "{{ item }}"
        dest: "./"
        owner: pi
        mode: '0700'
      with_items:
        - "reboot.sh"
        - "shutdown.sh"

    # Reboot if necessary
        
    - name: Check if a reboot is needed for Debian box
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
      
 
    - name: Reboot the Debian server if needed
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
