---

- name: Setup or update the VM
  hosts: HomeVM
  remote_user: freebox
  become: yes
    
  tasks:
  
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Set timezone to Europe/Paris
      timezone:
        name: Europe/Paris

    - name: Change PasswordAuthentication to no in sshd_config file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: PasswordAuthentication no
        
    - name: Restart ssh service
      service:
        name: ssh
        state: restarted

    - name: Install rsync packages
      apt:
        name: rsync
        state: present

    - name: Downlad Docker install script
      get_url:
        url: https://get.docker.com/
        dest: ./get-docker.sh
    
    - name: Run Docker install script
      command: sh ./get-docker.sh           
      
    - name: Add freebox user to docker usersgroup
      command: usermod -aG docker freebox

    - name: Delete get-docker.sh file
      file:
        path: ./get-docker.sh
        state: absent
       
    - name: Install docker-compose
      get_url:
        url: https://github.com/AppTower/docker-compose/releases/download/1.25.4/run.sh
        dest: /usr/local/bin/docker-compose
        
    - name: Change compose script permission
      file:
        path: /usr/local/bin/docker-compose
        owner: freebox
        group: freebox
        mode: 0755
        
    - name: Check if a reboot is needed for Debian box
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
      
 
    - name: Reboot the Debian server if needed
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
...