---

- name: Install / update MyNas app
  hosts: HomeVM
  remote_user: freebox

  vars:
    project_root_dir: /Users/frederic/git/MyNAS/
    private_key_file: /Volumes/Vault2/ssh-keys/pi.wo.password/pi.raspberry
    mynas_app_dir: /home/freebox/MyNas
    install_archive: MyNAS_0.4.tar.gz

  tasks:

    - name: Create MyNas app directory 
      file:
        path: "{{ mynas_app_dir }}"
        state: directory

    - name: Copy archive install
      copy:
        src: "{{ project_root_dir }}/{{ install_archive }}"
        dest: "{{ mynas_app_dir }}"
        owner: freebox
        group: freebox

    - name: Copy private key
      copy:
        src: "{{ private_key_file }}"
        dest: .ssh/
        owner: freebox
        group: freebox
        mode: '0600'

    - name: Unarchive MyNas source
      command: "tar xzvf {{ mynas_app_dir }}/{{ install_archive }} -C {{ mynas_app_dir }}"
      register: output

    - name: Create MyNAS cron job chrisal-mauguio backup
      cron:
        name: "chrisal-mauguio backup"
        minute: "0"
        hour: "1"
        job: "{{ mynas_app_dir }}/BackupMain.py -v chrisal-mauguio" 

    - name: Create MyNAS cron job ornano-mauguio backup
      cron:
        name: "ornano-mauguio backup"
        minute: "0"
        hour: "2"
        job: "{{ mynas_app_dir }}/BackupMain.py -v ornano-mauguio"

    - name: Create MyNAS cron job mauguio-chrisal backup
      cron:
        name: "mauguio-chrisal backup"
        minute: "0"
        hour: "3"
        job: "{{ mynas_app_dir }}/BackupMain.py -v mauguio-chrisal" 
...