---

- name: Install / update Owncloud server
  hosts: HomeVM
  remote_user: freebox
  vars:
    project_root_dir: /Users/frederic/git/My-Banking-Agent
    owncloud_data_dir: /mnt/owncloud/data
    mariadb_backup_dir: /mnt/owncloud/db_backup

  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: "{{ project_root_dir }}/docker"
        dest: ./
        owner: freebox
        group: freebox

    - name: Create directories for external db_backup volume
      become: true
      file:
        path: "{{mariadb_backup_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create directories for external data volume
      become: true
      file:
        path: "{{owncloud_data_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Tear down existing Owncloud services stack
      command: docker-compose -p owncloud-server stop
      register: output
      args:
        chdir: ./docker/owncloud-server

    - name: Create and start Owncloud services stack
      command: docker-compose -p owncloud-server up -d
      register: output
      args:
        chdir: ./docker/owncloud-server
...