---

- name: Install / update MyNas app
  hosts: HomeVM
  remote_user: freebox

  vars:
    project_root_dir: /Users/frederic/git/MyNAS/
    private_key_file: /Volumes/Vault2/ssh-keys/pi.wo.password/pi.raspberry
    mynas_app_dir: /home/freebox/MyNas
    install_archive: MyNAS_0.5.tar.gz
    backup_plan_file: /Volumes/Vault2/mynas/backup_volume_path.py

  tasks:

    - name: Create MyNas app directory 
      file:
        path: "{{ mynas_app_dir }}"
        state: directory

    - name: Copy archive install
      copy:
        src: "{{ project_root_dir }}/{{ install_archive }}"
        dest: "{{ mynas_app_dir }}"
        owner: freebox
        group: freebox

    # Copy bash scripts (utlities)
    - copy:
        src: "{{ item }}"
        dest: "{{ mynas_app_dir }}"
        owner: freebox
        group: freebox
        mode: '0700'
      with_items:
        - "mount_chantal_freebox.sh"
        - "umount_chantal_freebox.sh"

    - name: Copy private key
      copy:
        src: "{{ private_key_file }}"
        dest: .ssh/
        owner: freebox
        group: freebox
        mode: '0600'

    - name: Unarchive MyNas source
      command: "tar xzvf {{ mynas_app_dir }}/{{ install_archive }} -C {{ mynas_app_dir }}"
      register: output

    - name: Copy backup plan
      copy:
        src: "{{ backup_plan_file }}"
        dest: "{{ mynas_app_dir }}"
        owner: freebox
        group: freebox
        mode: '0600'

    - name: Create MyNAS cron job chrisal-perols backup
      cron:
        state: present
        name: "chrisal-perols backup"
        minute: "0"
        hour: "1"
        job: "{{ mynas_app_dir }}/BackupMain.py -v chrisal-perols" 

    - name: Create MyNAS cron job ornano-perols backup
      cron:
        state: present
        disabled: no
        name: "ornano-perols backup"
        minute: "5"
        hour: "1"
        job: "{{ mynas_app_dir }}/mount_chantal_freebox.sh && {{ mynas_app_dir }}/BackupMain.py -v ornano-perols && {{ mynas_app_dir }}/umount_chantal_freebox.sh"

    - name: Create MyNAS cron job perols-chrisal backup
      cron:
        state: present
        name: "perols-chrisal backup"
        minute: "0"
        hour: "2"
        job: "{{ mynas_app_dir }}/BackupMain.py -v perols-chrisal" 
...