---

- name: Install / update Owncloud server
  hosts: raspberry
  remote_user: pi
  vars:
    docker_root_dir: ./owncloud-server
    owncloud_data_dir: /mnt/owncloud/data
    mariadb_backup_dir: /mnt/owncloud/db_backup
    owncloud_files_bck_dir: /mnt/owncloud/files_backup
    bkscript_dir: /home/pi/owncloud-server

  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: "{{ docker_root_dir }}"
        dest: ./

    - name: +x permissions to backup_mariadb script
      ansible.builtin.file:
        path: "{{ bkscript_dir }}/backup_mariadb.sh"
        mode: '0755'

    - name: +x permissions to backup_jaudin_files script
      ansible.builtin.file:
        path: "{{ bkscript_dir }}/backup_jaudin_files.sh"
        mode: '0755'

    - name: Create directories for external db_backup volume
      become: true
      file:
        path: "{{mariadb_backup_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create directories for external files backup 
      become: true
      file:
        path: "{{owncloud_files_bck_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create directories for external data volume
      become: true
      file:
        path: "{{owncloud_data_dir}}"
        state: directory
        owner: www-data
        group: www-data

    # - name: Tear down existing Owncloud services stack
    #   command: docker-compose -p owncloud-server stop
    #   register: output
    #   args:
    #     chdir: ./owncloud-server

    # - name: Create and start Owncloud services stack
    #   command: docker-compose -p owncloud-server up -d
    #   register: output
    #   args:
    #     chdir: ./owncloud-server

    - name: Create Owncloud database backup cron job
      cron:
        user: pi
        name: "Owncloud database backup"
        minute: "30"
        hour: "00"
        job: "{{ bkscript_dir }}/backup_mariadb.sh > /tmp/mariadb_backup_output.log 2>&1"

    - name: Create Owncloud Jaudin's files backup cron job
      cron:
        user: pi
        name: "Owncloud Jaudin Files backup"
        minute: "00"
        hour: "01"
        job: "sudo -u www-data {{ bkscript_dir }}/backup_jaudin_files.sh > /tmp/backup_jaudin_files.log 2>&1"
...