---

- name: Install / update Owncloud server
  hosts: raspberry
  remote_user: pi
  vars:
    docker_root_dir: ./owncloud-server
    owncloud_data_dir: /mnt/owncloud/data
    mariadb_backup_dir: /mnt/owncloud/db_backup

  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: "{{ docker_root_dir }}"
        dest: ./

    - name: Create directories for external db_backup volume
      become: true
      file:
        path: "{{mariadb_backup_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create directories for external data volume
      become: true
      file:
        path: "{{owncloud_data_dir}}"
        state: directory
        owner: www-data
        group: www-data

    - name: Tear down existing Owncloud services stack
      command: docker-compose -p owncloud-server stop
      register: output
      args:
        chdir: ./owncloud-server

    - name: Create and start Owncloud services stack
      command: docker-compose -p owncloud-server up -d
      register: output
      args:
        chdir: ./owncloud-server
...