---

- name: Install / update MBA app
  hosts: raspberry
  remote_user: pi
  become: true

  vars:
    project_root_dir: /Users/home/git/My-Banking-Agent/mba_app
    install_archive: mba_3.10.tar.gz
    mba_app_dir: /home/pi/mba_app
    owncloud_data_dir: /mnt/owncloud/data
    install_properties: /Volumes/Vault2/mba/app.txt
    install_auth: /Volumes/Vault2/mba/auth.pl

  tasks:

    - name: Add files_external_allow_create_new_local in config.php
      lineinfile:
        path: "{{ owncloud_data_dir }}/config/config.php"
        regexp: "^\\s*'files_external_allow_create_new_local' => 'true',$"
        insertbefore: '^\);$'
        line: "  'files_external_allow_create_new_local' => 'true',"
        state: present
        owner: www-data
        group: www-data

    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: "{{ project_root_dir }}"
        dest: ./
        owner: www-data
        group: www-data

    - name: build the mba:build image
      command: docker build -t mba:build ./mba_app/build
      register: output

    - name: build the mba:prod image
      command: docker build -t mba:prod ./mba_app/prod
      register: output

    - name: Create MBA app directory 
      file:
        path: "{{ mba_app_dir }}/prod/app"
        state: directory
        owner: www-data
        group: www-data

    - name: Unarchive MBA source
      command: "tar xzvf {{ mba_app_dir }}/prod/{{ install_archive }} -C {{ mba_app_dir }}/prod/app"
      register: output

    - name: Recursively change ownership of a directory
      file:
        path: "{{ mba_app_dir }}/prod/app"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Copy file app.txt
      copy: 
        src: "{{ install_properties }}"
        dest: "{{ mba_app_dir }}/prod/app/properties"
        owner: www-data
        group: www-data

    - name: Copy file auth.pl
      copy: 
        src: "{{ install_auth }}"
        dest: "{{ mba_app_dir }}/prod/app"
        mode: '0600'
        owner: www-data
        group: www-data

    - name: Set mba_run.sh to executable
      file: 
        path: "{{ mba_app_dir }}/run_mba.sh"
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Create MBA cron job
      cron:
        user: pi
        name: "MBA"
        minute: "30"
        hour: "20"
        job: "{{ mba_app_dir }}/run_mba.sh > /tmp/mba_output.log 2>&1"
...